import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:threadhub_system/Tailor/pages/menu%20item/tailor_profilesettings/help%20center/chatbox.dart';
import 'package:threadhub_system/Tailor/pages/menu%20item/tailor_profilesettings/tailor_fontprovider.dart';

class TailorHelpPage extends StatefulWidget {
  const TailorHelpPage({super.key});

  @override
  State<TailorHelpPage> createState() => _TailorHelpPageState();
}

class _TailorHelpPageState extends State<TailorHelpPage> {
  final List<Map<String, String>> faqList = [
    {
      "question": "How do I manage my orders?",
      "answer":
          "You can manage your orders through the 'List of Workload' section in your dashboard. Here, you can view new orders, update their status, and communicate with customers.",
    },
    {
      "question": "How do I set my availability?",
      "answer": "Go to your profile settings and select availability options.",
    },
    {
      "question": "How do I respond to customer inquiries?",
      "answer":
          "Use the messaging feature in the dashboard to reply to inquiries.",
    },
    {
      "question": "What should I do if I encounter a technical issue?",
      "answer": "Contact support via the 'Contact Us' tab for assistance.",
    },
    {
      "question": "How can I showcase my portfolio?",
      "answer": "Upload samples in your profile under 'Portfolio' section.",
    },
    {
      "question": "How do I receive notifications?",
      "answer": "Enable push notifications in app settings.",
    },
    {
      "question": "How do I update my pricing or service?",
      "answer": "Simply find a pen icon on the workload list.",
    },

    // new tab
    {
      "question": "Can I set deadlines for orders?",
      "answer":
          "No, because the customer selects the date for their deadline, but you have the option to accept or decline the appointment booking.",
    },
    {
      "question":
          "How do I handle revisions or alterations requested by customer?",
      "answer":
          "You can address it through chat if you need clarification on the request, but since the system allows customers to submit photographs or files as well as their appointment booking instructions, there is no need to worry about it.",
    },
    {
      "question": "How do I track the performance of the shop?",
      "answer": "You may access the Shop Performance Report via the menu bar.",
    },
    {
      "question": "How do I manage cancellations?",
      "answer":
          "You can cancel or reject appointment bookings using the buttons located below the appointment tables on pending lists.",
    },
    {
      "question": "Can I offer discounts and promotions?",
      "answer":
          "Yes, however it is between you and the consumer throughout the pricing process.",
    },
    {
      "question": "How do I improve my visibility to customers?",
      "answer":
          "You can improve your visibility by uploading high-quality images to your portfolio, keeping your profile details complete and up to date, responding quickly to customer inquiries, and maintaining positive reviews. Offering clear descriptions of your services and showcasing your best work also helps attract more customers.",
    },
    {
      "question": "How are disputes resolved?",
      "answer":
          "If you and the customer are unable to communicate effectively, you can report the customer using the report button, which is also visible in the appointment table.",
    },
    {
      "question": "How do I update my profile and contact information?",
      "answer":
          "You can update this information through Profile Settings; simply find the Personal Information section and edit it.",
    },
    {
      "question": "How do I schedule fittings or appointments with customers?",
      "answer":
          "The schedule for both is centralized and generated by the customers themselves; the system will notify you of specific customers nearby, and you can see the appointment date and their product due date; however, if you wanted the appointment but couldn't compress your schedule, you can update the customer to update the date if they accept it.",
    },
    {
      "question": "How do I mark an order as completed or notify the customer?",
      "answer":
          "There is a mark as done button in the appointment table that you can click if the product is finished and alert them when it is available for collection.",
    },
    {"question": "How can I get customer reviews and ratings?", "answer": ""},
    {
      "question": "Can I manage bulk or group orders(e.g uniforms, outfits)",
      "answer":
          "The choice is up to you, however the system will alert you at any time when you customer arrange an appointment related to your skillsets.",
    },
    {
      "question":
          "How do I update the status of an order(Approve this Appointment, Cancel, and Notify Customer)?",
      "answer": "",
    },
    {
      "question": "Can I message customer directly through the system?",
      "answer":
          "Yes, you can message the customer on the right side under their name.",
    },
    {
      "question":
          "What happens if a customer doesn't show up for a first appointment or pickup?",
      "answer":
          "You can either cancel the appointment if the person scheduled does not show up without notice, alert the customer if they do not pick it up within the specified timeframe, or call and text them if necessary, as the appointment includes the customer's personal information such as their name and phone number.",
    },

    //newly update faqs
    {
      "question": "Can I save customer measurements for future use?",
      "answer":
          "The answer is system itself has already have saving function once the appointment booking is finished it will go to the completed list whereas tailors like you can search it anytime, so no need to worried to having save it.",
    },
    {
      "question": "How do I upload fabric options or style catalogs?",
      "answer":
          "You can upload photos of fabrics, catalogs, or sample styles in the Portfolio section, and description making it easier for customers to choose their preferences.",
    },
    {
      "question": "How do I manage refunds?",
      "answer":
          "Refunds are managed manually between you and the customer. Make sure to document the reason for the refund and update the order status accordingly.",
    },
    {
      "question": "Can I reschedule a customer’s appointment?",
      "answer":
          "Yes, you can propose a new date and time for the appointment through the chat or reschedule option. The customer will be notified and must confirm.",
    },
    {
      "question": "How do I showcase special offers or seasonal collections?",
      "answer":
          "You can update your portfolio with seasonal looks or limited-time promotions, and share them with customers directly through the chat feature.",
    },
    {
      "question": "Can I receive reminders for upcoming deadlines?",
      "answer":
          "Yes, the system sends you reminders for upcoming fittings, deadlines, and order completion dates through notifications.",
    },
    {
      "question": "How do I handle urgent or rush orders?",
      "answer":
          "When customers request urgent orders, you’ll see a priority tag in the workload list. You can choose to accept or decline based on your availability.",
    },
    {
      "question": "Can I view customer history?",
      "answer":
          "Yes, you can view past orders, measurements, and feedback from each customer in their profile section.",
    },
    {
      "question": "How do I get support if my account is suspended?",
      "answer":
          "If your account is suspended, contact support immediately through the Help Center. Provide your registered email and order details for faster resolution.",
    },
  ];
  @override
  Widget build(BuildContext context) {
    final tailorfontSize = context.watch<TailorFontprovider>().fontSize;
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        backgroundColor: const Color(0xFFEFEFEF),
        appBar: AppBar(
          backgroundColor: const Color(0xFF262633),
          iconTheme: const IconThemeData(color: Colors.white),
          title: Text(
            "Help Center",
            style: GoogleFonts.prompt(
              color: Colors.white,
              fontWeight: FontWeight.w600,
              fontSize: tailorfontSize,
            ),
          ),
          bottom: PreferredSize(
            preferredSize: const Size.fromHeight(48),
            child: Container(
              color: const Color(0xFFD9D9D9),
              child: TabBar(
                indicatorColor: Colors.black,
                indicatorSize: TabBarIndicatorSize.label,

                labelColor: Colors.black,
                unselectedLabelColor: Colors.grey,
                labelStyle: GoogleFonts.prompt(
                  fontWeight: FontWeight.w600,
                  fontSize: tailorfontSize,
                ),
                tabs: [
                  Tab(text: "FAQ"),
                  Tab(text: "Contact Us"),
                ],
              ),
            ),
          ),
        ),

        body: Container(
          color: const Color(0xFFD9D9D9),
          child: TabBarView(
            children: [
              //FAQ TAB
              Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.all(12.0),
                    child: TextField(
                      decoration: InputDecoration(
                        hintText: "Search for help",
                        hintStyle: GoogleFonts.prompt(),
                        prefixIcon: const Icon(Icons.search),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: BorderSide.none,
                        ),
                      ),
                    ),
                  ),
                  Expanded(
                    child: ListView.builder(
                      itemCount: faqList.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 12,
                            vertical: 6,
                          ),
                          child: Card(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5),
                              side: BorderSide.none,
                            ),
                            child: ExpansionTile(
                              title: Text(
                                faqList[index]["question"]!,
                                style: GoogleFonts.prompt(
                                  fontWeight: FontWeight.w600,
                                  fontSize: tailorfontSize,
                                ),
                              ),
                              children: [
                                Padding(
                                  padding: const EdgeInsets.all(12.0),
                                  child: Text(
                                    faqList[index]["answer"]!,
                                    style: GoogleFonts.prompt(
                                      color: Colors.grey[700],
                                      fontSize: tailorfontSize,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),

              //CONTACT US TAB
              Container(
                color: const Color(0xFFD9D9D9),
                child: ListView(
                  padding: const EdgeInsets.all(16),
                  children: [
                    _buildContactCard(
                      icon: Icons.headset_mic,
                      text: "Customer Services Assistance",
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(builder: (_) => const ChatPage()),
                        );
                      },
                    ),
                    _buildContactCard(
                      icon: Icons.whatshot,
                      text: "Technical Support Hotline",
                    ),
                    _buildContactCard(
                      icon: Icons.email,
                      text: "developersname@gmail.com",
                    ),
                    _buildContactCard(
                      icon: Icons.facebook,
                      text: "www.facebook.com/developersname",
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildContactCard({
    required IconData icon,
    required String text,
    VoidCallback? onTap,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(20),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            boxShadow: [
              BoxShadow(
                color: Colors.black12,
                blurRadius: 6,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Row(
            children: [
              Icon(icon, size: 28, color: Colors.black),
              const SizedBox(width: 16),
              Expanded(
                child: Text(
                  text,
                  style: GoogleFonts.prompt(
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                    color: Colors.black,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
